# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: starefossen/ruby-node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

stages:
  - build
  - deploy
  
cache:
  paths:
  - node_modules/

install_dependencies:
  stage: build
  script:
   - npm install uglify-js -g
   - gem install sass
   - gem install scss

build_website:
  stage: build
  script:
   - npm install
   - npm run build

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -r ./site ./public
  artifacts:
    paths:
    - public
  only:
  - newest